// Bundles each hook into one CommonJS file for the Bob kit (R5 §1: format cjs, platform node, target node20).
// Output: bob-kit/coder/.bob/hooks/<name>.js. The kit ships .bob/package.json {"type":"commonjs"} so a
// workspace with "type": "module" still runs them as CommonJS (fase 01 finding, D-umar-01).
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const HOOKS = ['brief', 'lock_guard', 'mark_ai_edit', 'stop'];
const src = (f) => fileURLToPath(new URL(`./src/${f}.ts`, import.meta.url));
const outdir = fileURLToPath(new URL('../../bob-kit/coder/.bob/hooks/', import.meta.url));

await build({
  entryPoints: HOOKS.map(src),
  outdir,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  minify: false,
  legalComments: 'none',
  banner: { js: '#!/usr/bin/env node\n// generated by @radar/hooks — do not edit' },
  logLevel: 'info',
});
