// Bundles radar-mcp into one CommonJS file for the Bob kit (R5 §1). Output: bob-kit/coder/.bob/radar-mcp.js.
// fase 08 adds bob-kit/pm/.bob/radar-mcp.js (same file; the role comes from .radar/local.json).
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const outfiles = ['../../bob-kit/coder/.bob/radar-mcp.js'].map((f) => fileURLToPath(new URL(f, import.meta.url)));

for (const outfile of outfiles) {
  await build({
    entryPoints: [fileURLToPath(new URL('./src/main.ts', import.meta.url))],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node20',
    minify: false,
    legalComments: 'none',
    banner: { js: '#!/usr/bin/env node\n// generated by @radar/mcp — do not edit' },
    logLevel: 'info',
  });
}
