/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 5e009a95bc69107e086b1438b2b26813)
interface __BaseEnv_Env {
	WORKSPACE_ID: string;
	CORS_ORIGIN: string;
	PUBLIC_EXPORT: string;
	BOB_COAUTHOR: string;
	AUTO_APPLY_QUEUE: string;
	GITHUB_REPO: string;
	GITHUB_COMMIT: string;
	LOG_LEVEL: string;
	WORKSPACE: DurableObjectNamespace<import("./src/index").WorkspaceDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKSPACE_ID" | "CORS_ORIGIN" | "PUBLIC_EXPORT" | "BOB_COAUTHOR" | "AUTO_APPLY_QUEUE" | "GITHUB_REPO" | "GITHUB_COMMIT" | "LOG_LEVEL">> {}
}
