/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a30546cce2ae3fb21def1ded627caa67)
interface __BaseEnv_Env {
  WORKSPACE_ID: 'toko-demo';
  GITHUB_COMMIT: 'false';
  LOG_LEVEL: 'info';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'WORKSPACE_ID' | 'GITHUB_COMMIT' | 'LOG_LEVEL'>
  > {}
}
