#!/usr/bin/env node
// generated by @radar/hooks — do not edit
"use strict";

// src/_shared.ts
var import_node_fs2 = require("node:fs");
var import_node_path2 = require("node:path");

// src/placeholder/common.ts
var import_node_fs = require("node:fs");
var import_node_path = require("node:path");
var HOOK_SERVER_TIMEOUT_MS = 1500;
var ACTIVITY_TIMEOUT_MS = 800;
var EDIT_TOOLS_REGEX = /^(write_file|apply_diff|search_and_replace|insert_content|office_edit)$/;
var EVENTS = ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop"];
var isObj = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
var str = (v) => typeof v === "string" && v.length > 0 ? v : null;
function pick(o, ...keys) {
  for (const k of keys) if (o[k] !== void 0) return o[k];
  return void 0;
}
function collectPaths(input) {
  const out = [];
  const push = (v) => {
    const s = str(v);
    if (s) out.push(s);
  };
  for (const k of ["path", "file_path", "filePath", "target_file"]) push(input[k]);
  const args = input.args;
  if (isObj(args)) {
    push(args.path);
    if (Array.isArray(args.file)) {
      for (const f of args.file) if (isObj(f)) push(f.path);
    }
  }
  if (Array.isArray(input.files)) {
    for (const f of input.files) if (isObj(f)) push(f.path);
  }
  return out;
}
function toWorkspaceRelative(root, p) {
  const posix = p.replace(/\\/g, "/");
  const abs = (0, import_node_path.isAbsolute)(posix) ? posix : (0, import_node_path.resolve)(root, posix);
  const rel = (0, import_node_path.relative)(root, abs);
  if (rel === "" || rel.startsWith("..") || (0, import_node_path.isAbsolute)(rel)) return null;
  return rel.split(import_node_path.sep).join("/");
}
function normalizeHookPayload(raw, root) {
  const o = isObj(raw) ? raw : {};
  const eventName = str(pick(o, "hook_event_name", "hookEventName", "event"));
  const event = eventName && EVENTS.includes(eventName) ? eventName : "unknown";
  const inputRaw = pick(o, "tool_input", "toolInput", "input");
  const input = isObj(inputRaw) ? inputRaw : {};
  const paths = [
    ...new Set(collectPaths(input).map((p) => toWorkspaceRelative(root, p)).filter((p) => p !== null))
  ];
  return {
    event,
    tool: str(pick(o, "tool_name", "toolName", "tool")),
    paths,
    sessionId: str(pick(o, "session_id", "sessionId")),
    cwd: str(o.cwd),
    prompt: typeof o.prompt === "string" ? o.prompt : null,
    input,
    raw
  };
}
var ConfigMissingError = class extends Error {
};
function findLocalJson(startDir) {
  let dir = (0, import_node_path.resolve)(startDir);
  for (; ; ) {
    const f = (0, import_node_path.join)(dir, ".radar", "local.json");
    if ((0, import_node_fs.existsSync)(f)) return f;
    const parent = (0, import_node_path.dirname)(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
function loadLocalConfig(startDir, env = process.env) {
  const base = env.RADAR_ROOT ? (0, import_node_path.resolve)(env.RADAR_ROOT) : startDir;
  const file = findLocalJson(base);
  let fromFile = {};
  if (file) {
    const parsed = JSON.parse((0, import_node_fs.readFileSync)(file, "utf8"));
    if (isObj(parsed)) fromFile = parsed;
  }
  const root = env.RADAR_ROOT ? (0, import_node_path.resolve)(env.RADAR_ROOT) : file ? (0, import_node_path.dirname)((0, import_node_path.dirname)(file)) : (0, import_node_path.resolve)(startDir);
  const server = env.RADAR_SERVER ?? str(fromFile.server);
  const token = env.RADAR_TOKEN ?? str(fromFile.token);
  if (!server || !token) throw new ConfigMissingError(`no .radar/local.json (server, token) found from ${base}`);
  const role = (env.RADAR_ROLE ?? str(fromFile.role)) === "pm" ? "pm" : "coder";
  return {
    root,
    server: server.replace(/\/+$/, ""),
    workspace: str(fromFile.workspace) ?? "",
    member: env.RADAR_MEMBER ?? str(fromFile.member) ?? "",
    token,
    role,
    shareprompts: env.RADAR_SHAREPROMPTS ? env.RADAR_SHAREPROMPTS === "true" : fromFile.shareprompts === true
  };
}
var stateFile = (root) => (0, import_node_path.join)(root, ".radar", "state.json");
function loadState(root) {
  try {
    const parsed = JSON.parse((0, import_node_fs.readFileSync)(stateFile(root), "utf8"));
    return isObj(parsed) ? parsed : {};
  } catch {
    return {};
  }
}
function saveState(root, patch) {
  const next = { ...loadState(root), ...patch };
  const file = stateFile(root);
  (0, import_node_fs.mkdirSync)((0, import_node_path.dirname)(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  (0, import_node_fs.writeFileSync)(tmp, JSON.stringify(next, null, 2));
  (0, import_node_fs.renameSync)(tmp, file);
}

// src/_shared.ts
var STDIN_TIMEOUT_MS = 500;
function readStdin(timeoutMs = STDIN_TIMEOUT_MS) {
  return new Promise((resolve2) => {
    let raw = "";
    const done = () => {
      clearTimeout(timer);
      resolve2(raw);
    };
    const timer = setTimeout(done, timeoutMs);
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => raw += chunk);
    process.stdin.on("end", done);
    process.stdin.on("error", done);
  });
}
function parseJson(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}
function logLine(root, hook, message) {
  if (!root) return;
  try {
    const dir = (0, import_node_path2.join)(root, ".radar");
    (0, import_node_fs2.mkdirSync)(dir, { recursive: true });
    (0, import_node_fs2.appendFileSync)((0, import_node_path2.join)(dir, "hook.log"), `${(/* @__PURE__ */ new Date()).toISOString()} ${hook} ${message}
`);
  } catch {
  }
}
async function loadContext(hookName) {
  const started = Date.now();
  const raw = parseJson(await readStdin());
  const payloadCwd = raw && typeof raw === "object" && typeof raw.cwd === "string" ? raw.cwd : process.cwd();
  let cfg;
  try {
    cfg = loadLocalConfig(payloadCwd);
  } catch (err) {
    if (!(err instanceof ConfigMissingError)) logLine(payloadCwd, hookName, `config error: ${String(err)}`);
    return null;
  }
  return { cfg, hook: normalizeHookPayload(raw, cfg.root), started };
}
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
  status;
};
async function radarFetch(cfg, method, path, body, timeoutMs) {
  const res = await fetch(`${cfg.server}${path}`, {
    method,
    headers: {
      authorization: `Bearer ${cfg.token}`,
      ...body === void 0 ? {} : { "content-type": "application/json" }
    },
    body: body === void 0 ? void 0 : JSON.stringify(body),
    signal: AbortSignal.timeout(timeoutMs)
  });
  if (!res.ok) throw new HttpError(res.status, `${method} ${path} \u2192 ${res.status}`);
  if (res.status === 204) return void 0;
  return await res.json();
}
var modeOf = (cfg) => cfg.role === "pm" ? "pm-lead" : "coder";
function settleWithin(p, ms) {
  return new Promise((resolve2) => {
    const timer = setTimeout(resolve2, Math.max(0, ms));
    p.then(
      () => {
        clearTimeout(timer);
        resolve2();
      },
      () => {
        clearTimeout(timer);
        resolve2();
      }
    );
  });
}

// src/activity.ts
var PROMPT_TEXT_MAX = 200;
function buildActivity(cfg, fields, now = Date.now()) {
  const { text, ...rest } = fields;
  const body = { ...rest, mode: modeOf(cfg), clientTs: now };
  if (cfg.shareprompts && text) body.text = text.length > PROMPT_TEXT_MAX ? `${text.slice(0, PROMPT_TEXT_MAX - 1)}\u2026` : text;
  return body;
}
async function sendActivity(cfg, fields) {
  try {
    await radarFetch(cfg, "POST", "/v1/bob/activity", buildActivity(cfg, fields), ACTIVITY_TIMEOUT_MS);
  } catch (err) {
    logLine(cfg.root, "activity", `${fields.kind} not sent: ${String(err)}`);
  }
}

// src/lock_guard.ts
async function main() {
  const ctx = await loadContext("lock_guard");
  if (!ctx) return;
  const { cfg, hook, started } = ctx;
  const tool = hook.tool ?? "";
  if (!EDIT_TOOLS_REGEX.test(tool) || hook.paths.length === 0) return;
  let res;
  try {
    res = await radarFetch(
      cfg,
      "POST",
      "/v1/locks/check",
      { paths: hook.paths, tool, sessionId: hook.sessionId, clientTs: Date.now() },
      HOOK_SERVER_TIMEOUT_MS
    );
  } catch (err) {
    logLine(cfg.root, "lock_guard", `locks/check failed: ${String(err)}`);
    return;
  }
  const decision = res.decision;
  const durationMs = Date.now() - started;
  logLine(cfg.root, "lock_guard", `decision=${decision} tool=${tool} ms=${durationMs}`);
  await settleWithin(
    sendActivity(cfg, {
      kind: "tool.pre",
      sessionId: hook.sessionId,
      tool,
      paths: hook.paths,
      decision
    }),
    300
  );
  if (decision === "block") {
    process.stderr.write(res.message + "\n");
    try {
      const blocked = res.results.find((r) => r.decision === "block")?.path ?? hook.paths[0] ?? "";
      saveState(cfg.root, { lastBlock: { path: blocked, message: res.message, ts: Date.now() } });
    } catch (err) {
      logLine(cfg.root, "lock_guard", `lastBlock not saved: ${String(err)}`);
    }
    process.exit(2);
  }
}
main().catch(() => void 0).finally(() => process.exit(0));
